#!/bin/bash
###################################################################
#CREATOR: 05remla@gmail.com
#DATE: last modified APR.11,2025
#PURPOSE: display ipv4 information of specified (or defualt) iface
###################################################################
ARGS=($@)
function help()
{
    echo "Options"
    echo "--iface= | -i=   specify iface"
    echo "--lan    | -l    show lan address"
    echo "--wan    | -w    show wan address"
    echo "--net    | -n    show local net"
    echo
}


function test()                                                                                                                                                                    
{                                                                                                                                                                                  
    test_state=$(cat /sys/class/net/${iface}/operstate)                                                                                                                            
    if [[ $test_state == "down" ]]; then                                                                                                                                           
        echo "${iface} down. exiting."                                                                                                                                             
        exit 1                                                                                                                                                                       
    fi                                                                                                                                                                             
}


# if no args passed display help info
if [[ $(echo ${ARGS[@]} | wc -w) == 0 ]]; then
    help
    exit 0
fi


# check args for iface decleration
for arg in ${ARGS[@]}
do
    case $arg in
        '--iface='*|'-f='*)
            iface=$(echo $arg | cut -d= -f2)
        ;;
    esac
done


# if iface not declared use iface from default route
if [[ -z "$iface" ]]; then
    iface=$(ip route | grep default | awk '{print $5}')
fi


# analyze all args
for arg in ${ARGS[@]}
do
    case $arg in
        '--lan'|'-l')
            test
            LAN=$(ifconfig $iface | grep 'inet ' | awk '{print $2}')
            echo $LAN
        ;;

        '--wan'|'-w')
            test
            WAN=$(curl -s 'https://api.ipify.org')
            echo $WAN
        ;;

        '--net'|'-n')
            test
            ip route | grep $iface | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1\}[/][0-9]\{1,3\}'
        ;;

        '-h'|'--help')
            help
            exit 0
        ;;

    esac
done

exit 0
